dist: trusty
sudo: true
language: node_js
node_js:
  - "6"
cache: yarn
env:
  global:
    - SHIPPR_ENV=travis
    - SHIPPR_NOTIFY_SERVICE=github
    - SHIPPR_APP_SLUG=TryShippr
script:
  - 'yarn test'
after_success:
  - 'SHIPPR_EVENT="$TRAVIS_EVENT_TYPE" yarn shippr'
deploy:
  provider: script
  script: 'SHIPPR_EVENT=release yarn shippr'
  skip_cleanup: true
  on:
    branch: master
