dist: trusty
sudo: true
before_install:
  - yarn add --dev exp
language: node_js
node_js:
  - "6"
cache: yarn
env:
  global:
    - SHIPPR_ENV=travis
    - SHIPPR_NOTIFY_SERVICE=github
    - SHIPPR_APP_SLUG=tryshippr
    - EXPO_DEBUG=true
script:
  - 'yarn test'
after_success:
  - '[ "$TRAVIS_EVENT_TYPE" = "pull_request" ] && SHIPPR_EVENT="$TRAVIS_EVENT_TYPE" yarn shippr'
